import * as React from "react";
import '../css/navbar.css';
import { Arrow, RedFolder, LightRedFolder, NormalFile, ProjectIcon, StopIcon, UndoIcon, PlayIcon, BlueFolder, GreenFolder, YellowFolder, READMEIcon } from "./Components";
export default class Navbar extends React.Component {
    render() {
        return (React.createElement("div", { className: "navbar" },
            React.createElement("div", { className: "header" },
                React.createElement("div", { className: "title" }, "Vagus"),
                React.createElement("div", { className: "description" }, "[\u201Cpathfinding algorithms\u201D][\u201CLatin\u201D:\u201Dwandering\u201D]")),
            React.createElement("div", { className: "project" },
                React.createElement(ProjectIcon, null),
                React.createElement("p", { className: "project-title" }, "Project"),
                React.createElement("div", { className: "buttons" },
                    React.createElement(StopIcon, null),
                    React.createElement(UndoIcon, null),
                    React.createElement(PlayIcon, null))),
            React.createElement("div", { className: "drops" },
                React.createElement("div", { className: "master-drop drop" },
                    React.createElement(Arrow, null),
                    React.createElement(RedFolder, null),
                    React.createElement("div", { className: "drop-title" },
                        "Vagus-master",
                        React.createElement("span", { className: "bold-it" }, "[vagus]"))),
                React.createElement("div", { className: "master-line line" },
                    React.createElement("div", { className: "master-control-drop drop" },
                        React.createElement(Arrow, null),
                        React.createElement(RedFolder, null),
                        React.createElement("div", { className: "drop-title" }, "master-control-panel")),
                    React.createElement("div", { className: "master-cp-line line" },
                        React.createElement("div", { className: "advanced-control-drop drop" },
                            React.createElement(Arrow, null),
                            React.createElement(RedFolder, null),
                            React.createElement("div", { className: "drop-title" }, "advanced-control-panel")),
                        React.createElement("div", { className: "advanced-cp-line line" },
                            React.createElement("div", { className: "algorithm-drop drop" },
                                React.createElement(Arrow, null),
                                React.createElement(LightRedFolder, null),
                                React.createElement("div", { className: "drop-title" }, "algorithms")),
                            React.createElement("div", { className: "algorithms line" },
                                React.createElement("div", { className: "alg-1 drop-file" },
                                    React.createElement(NormalFile, null),
                                    React.createElement("p", { className: "alg-name file-name" }, "aStarSearch.tsx")),
                                React.createElement("div", { className: "alg-2 drop-file" },
                                    React.createElement(NormalFile, null),
                                    React.createElement("p", { className: "alg-name file-name" }, "djikstrasSearch.tsx")),
                                React.createElement("div", { className: "alg-3 drop-file" },
                                    React.createElement(NormalFile, null),
                                    React.createElement("p", { className: "alg-name file-name" }, "bellmanFord.tsx")),
                                React.createElement("div", { className: "alg-4 drop-file" },
                                    React.createElement(NormalFile, null),
                                    React.createElement("p", { className: "alg-name file-name" }, "breadthFirstSearch.tsx")),
                                React.createElement("div", { className: "alg-5 drop-file" },
                                    React.createElement(NormalFile, null),
                                    React.createElement("p", { className: "alg-name file-name" }, "depthFirstSearch.tsx")),
                                React.createElement("div", { className: "alg-6 drop-file" },
                                    React.createElement(NormalFile, null),
                                    React.createElement("p", { className: "alg-name file-name" }, "biDirectionalSearch.tsx"))),
                            React.createElement("div", { className: "add-node-drop drop" },
                                React.createElement(Arrow, null),
                                React.createElement(BlueFolder, null),
                                React.createElement("div", { className: "drop-title" }, "addableNodes")),
                            React.createElement("div", { className: "nodes line" },
                                React.createElement("div", { className: "node-1 drop-file" },
                                    React.createElement(NormalFile, null),
                                    React.createElement("p", { className: "node-name file-name" }, "weightNode.io")),
                                React.createElement("div", { className: "node-2 drop-file" },
                                    React.createElement(NormalFile, null),
                                    React.createElement("p", { className: "node-name file-name" }, "bombNode.io")),
                                React.createElement("div", { className: "node-3 drop-file" },
                                    React.createElement(NormalFile, null),
                                    React.createElement("p", { className: "node-name file-name" }, "wallNode.io"))),
                            React.createElement("div", { className: "mazes-drop drop" },
                                React.createElement(Arrow, null),
                                React.createElement(GreenFolder, null),
                                React.createElement("div", { className: "drop-title" }, "mazes")),
                            React.createElement("div", { className: "mazes line" },
                                React.createElement("div", { className: "maze-1 drop-file" },
                                    React.createElement(NormalFile, null),
                                    React.createElement("p", { className: "maze-name file-name" }, "gridMaze.bat")),
                                React.createElement("div", { className: "maze-2 drop-file" },
                                    React.createElement(NormalFile, null),
                                    React.createElement("p", { className: "maze-name file-name" }, "randomMaze.bat")),
                                React.createElement("div", { className: "maze-3 drop-file" },
                                    React.createElement(NormalFile, null),
                                    React.createElement("p", { className: "maze-name file-name" }, "diagonalCutMaze.bat"))),
                            React.createElement("div", { className: "speed-drop drop" },
                                React.createElement(Arrow, null),
                                React.createElement(YellowFolder, null),
                                React.createElement("div", { className: "drop-title" }, "speeds")),
                            React.createElement("div", { className: "speed line" },
                                React.createElement("div", { className: "speed-1 drop-file" },
                                    React.createElement(NormalFile, null),
                                    React.createElement("p", { className: "speed-name file-name" }, "25percent.sys")),
                                React.createElement("div", { className: "speed-2 drop-file" },
                                    React.createElement(NormalFile, null),
                                    React.createElement("p", { className: "speed-name file-name" }, "50percent.sys")),
                                React.createElement("div", { className: "speed-3 drop-file" },
                                    React.createElement(NormalFile, null),
                                    React.createElement("p", { className: "speed-name file-name" }, "100percent.sys"))))),
                    React.createElement("div", { className: "read-me" },
                        React.createElement("div", { className: "speed-1 drop-read" },
                            React.createElement(READMEIcon, null),
                            React.createElement("p", { className: "speed-name file-name" }, "legend.md")),
                        React.createElement("div", { className: "speed-1 drop-read" },
                            React.createElement(READMEIcon, null),
                            React.createElement("p", { className: "speed-name file-name" }, "README.md")))))));
    }
}
